site_name: SensRNet Documentation
docs_dir: docs
site_dir: site
site_url: http://localhost:8000
repo_url: https://github.com/kadaster-labs/sensrnet-home
edit_uri: edit/main/docs/
nav:
    - 'General':
      - Overview: README.md
      - Contributors: Contributors.md
      - ProductVision.md
      - ProductVisionNL.md
      - SystemDescriptionNL.md
    - 'Architecture':
      - Overview: Architecture.md
      - KeyConcepts.md
      - Architectural Decision Records (ARDs): adr/index.md
      - Network.md
      - Model.md
      - Definitions.md
      - Blockchain.md
    - 'Functional':
      - User Manual (NL): UserManualNL.md
      - Use Cases (NL): UseCasesNL.md
      - TestScenariosNL.md
    - 'Technical':
      - Overview: Deployment.md
      - Multichain: SyncMultiChainEN.md
    - 'Organisation':
      - Functional Advisory Board: FAB.md
      - Pilots: Pilots.md
      - Users Group: UsersGroup.md
      - Notes: notes/index.md
      - Project Board: https://github.com/orgs/kadaster-labs/projects/1?fullscreen=true
extra_css:
  - css/sensrnet.css
theme:
  name: material
  features:
    - navigation.instant  
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  palette:
    primary: indigo
    accent: amber
  icon:
    logo: material/antenna
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
    
